"""first

Revision ID: b6e3e4d3a48b
Revises: 
Create Date: 2023-07-02 03:14:42.841851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e3e4d3a48b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pais_continente')
    op.drop_table('pais_lenguaje')
    op.drop_index('ix_lenguajes_id', table_name='lenguajes')
    op.drop_table('lenguajes')
    op.drop_index('ix_monedas_id', table_name='monedas')
    op.drop_table('monedas')
    op.drop_index('ix_paises_id', table_name='paises')
    op.drop_table('paises')
    op.drop_index('ix_capitales_id', table_name='capitales')
    op.drop_table('capitales')
    op.drop_index('ix_continentes_id', table_name='continentes')
    op.drop_table('continentes')
    op.drop_table('pais_moneda')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais_moneda',
    sa.Column('pais_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('moneda_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['moneda_id'], ['monedas.id'], name='pais_moneda_moneda_id_fkey'),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], name='pais_moneda_pais_id_fkey')
    )
    op.create_table('continentes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('continentes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='continentes_pkey'),
    sa.UniqueConstraint('nombre', name='continentes_nombre_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_continentes_id', 'continentes', ['id'], unique=False)
    op.create_table('capitales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('capital', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pais_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], name='capitales_pais_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='capitales_pkey'),
    sa.UniqueConstraint('capital', name='capitales_capital_key')
    )
    op.create_index('ix_capitales_id', 'capitales', ['id'], unique=False)
    op.create_table('paises',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('paises_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poblacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bandera', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='paises_pkey'),
    sa.UniqueConstraint('bandera', name='paises_bandera_key'),
    sa.UniqueConstraint('nombre', name='paises_nombre_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_paises_id', 'paises', ['id'], unique=False)
    op.create_table('monedas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('moneda', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='monedas_pkey'),
    sa.UniqueConstraint('moneda', name='monedas_moneda_key')
    )
    op.create_index('ix_monedas_id', 'monedas', ['id'], unique=False)
    op.create_table('lenguajes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('lenguajes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('lenguaje', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lenguajes_pkey'),
    sa.UniqueConstraint('lenguaje', name='lenguajes_lenguaje_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_lenguajes_id', 'lenguajes', ['id'], unique=False)
    op.create_table('pais_lenguaje',
    sa.Column('pais_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lenguaje_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lenguaje_id'], ['lenguajes.id'], name='pais_lenguaje_lenguaje_id_fkey'),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], name='pais_lenguaje_pais_id_fkey')
    )
    op.create_table('pais_continente',
    sa.Column('pais_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('continente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['continente_id'], ['continentes.id'], name='pais_continente_continente_id_fkey'),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], name='pais_continente_pais_id_fkey')
    )
    # ### end Alembic commands ###
